// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code  int
	Msg   string
	Token string
}

type Resp struct {
	Code    uint
	Message string
}

type UserInfo struct {
	Username string
	Password string
	Email    string
}
